<?php
$dblang_cart=array("ru"=>"Корзина","en"=>"Cart",);
$dblang_nick=array("ru"=>"Логин","en"=>"Login",);
$dblang_email=array("ru"=>"Email","en"=>"Email",);
$dblang_family=array("ru"=>"Имя Фамилия","en"=>"Full name",);
$dblang_gender=array("ru"=>"Пол","en"=>"Gender",);
$dblang_male=array("ru"=>"мужской","en"=>"Male",);
$dblang_female=array("ru"=>"женский","en"=>"Femail",);
$dblang_byear=array("ru"=>"Год рождения","en"=>"Year of birth",);
$dblang_yyyy=array("ru"=>"гггг","en"=>"yyyy",);
$dblang_phone=array("ru"=>"Телефон","en"=>"Phone",);
$dblang_country=array("ru"=>"Страна","en"=>"Country",);
$dblang_firm=array("ru"=>"Название организации","en"=>"Organisation name",);
$dblang_address=array("ru"=>"Адрес","en"=>"Address",);
$dblang_captcha=array("ru"=>"Код безопасности","en"=>"Security code",);
$dblang_register=array("ru"=>"Регистрация","en"=>"Register",);
$dblang_messok=array("ru"=>"На Ваш почтовый ящик отправлены данные для входа в аккаунт","en"=>"Your account data was sent to your mail box",);
$dblang_messerr=array("ru"=>"При регистрации произошла ошибка","en"=>"Registration error",);
$dblang_regsuccess=array("ru"=>"Вы зарегистрированы. Пароль отправлен на Ваш email.","en"=>"You had been registered. Your password was sent to your e-mail",);
$dblang_userexist=array("ru"=>"Такой участник уже есть в базе!","en"=>"This user already was registered!",);
$dblang_badcaptcha=array("ru"=>"Неверно введен проверочный код.","en"=>"Incorrect security code",);
$dblang_checknick=array("ru"=>"Укажите Логин.","en"=>"Input your Login",);
$dblang_badmail=array("ru"=>"Некорректный email.","en"=>"Incorrect e-mail",);
$dblang_enter=array("ru"=>"Войти","en"=>"Enter",);
$dblang_password=array("ru"=>"Пароль","en"=>"Password",);
$dblang_restore=array("ru"=>"Восстановление пароля","en"=>"Password recovery",);
$dblang_notfound=array("ru"=>"Пользовательне не найден","en"=>"User was not found",);
$dblang_order=array("ru"=>"Заказать","en"=>"Order",);
$dblang_check=array("ru"=>"Введите код безопастности","en"=>"Input security code",);
$dblang_attention=array("ru"=>"Внимание","en"=>"Attention",);
$dblang_yourdata=array("ru"=>"Ваши данные","en"=>"Your data",);
$dblang_change=array("ru"=>"Cохранить изменения","en"=>"Save changes",);
$dblang_welcome=array("ru"=>"Добро пожаловать","en"=>"Welcome",);
$dblang_logout=array("ru"=>"Выход","en"=>"Exit",);
$dblang_nouser=array("ru"=>"Участника с таким адресом в системе нет!","en"=>"There is no user with this e-mail address",);
$dblang_restoreSend=array("ru"=>"Ссылка для восстановления пароля отправлена Вам на почту.","en"=>"Link for password recovery was sent to your e-mail",);
$dblang_minPass=array("ru"=>"Минимальная длина пароля не менее 6 символов!","en"=>"The minimal password must be 6 signs long",);
$dblang_passChanged=array("ru"=>"Пароль изменен!","en"=>"The password has been changed!",);
$dblang_passRecovery=array("ru"=>"Восcтановление пароля","en"=>"Password recovery",);
$dblang_newPass=array("ru"=>"Введите новый пароль","en"=>"Input a new password",);
$dblang_restoreButton=array("ru"=>"Восстановить","en"=>"Recovery",);
$dblang_wrongLink=array("ru"=>"Неверная ссылка!","en"=>"Incorrect link!",);
$dblang_umail=array("ru"=>"Ваш почтовый ящик","en"=>"Your mailbox",);
$dblang_name=array("ru"=>"Имя","en"=>"Name",);
$dblang_title=array("ru"=>"Заголовок","en"=>"Title",);
$dblang_review=array("ru"=>"Ваш отзыв","en"=>"Your review",);
$dblang_makeReview=array("ru"=>"Оставить отзыв","en"=>"Make review",);
$dblang_positions=array("ru"=>"позиций","en"=>"positions",);
$dblang_total=array("ru"=>"на сумму","en"=>"total sum",);
$dblang_znak=array("ru"=>"&#8381.","en"=>"&#8381",);

?>